# Service 配置
apiVersion: v1
kind: Service
metadata:
  name: petclinic-db
spec:
  selector:
    app/name: petclinic-db  # Service 选择器，与 Pod 的标签匹配
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306  # 目标容器端口
  type: ClusterIP  # 内部通信类型
