apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.usePopulator: 'true'
  name: petclinic-db-dbdata
  namespace: petclinic

spec:
  preallocation: false
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
