apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/storage.usePopulator: 'true'
  name: inventory-db-dbdata
spec:
  preallocation: false
  source:
    blank: {}
  storage:
    resources:
      requests:
        storage: 10Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
---
# Service 配置
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app/name: inventory-db  # Service 选择器，与 Pod 的标签匹配
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432  # 目标容器端口
  type: ClusterIP  # 内部通信类型
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: inventory-db
  annotations:
    description: db
  labels:
    app: database
    os.template.kubevirt.io/fedora: 'true'
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      labels:
        app/name: inventory-db
        kubevirt.io/domain: example
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 2
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
            - disk:
                bus: virtio
              name: dbdata
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: q35
        memory:
          guest: 4Gi
      hostname: inventory-db
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: rootdisk
          containerDisk:
            image: quay.io/containerdisks/fedora
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              packages:
                - mariadb-server
              runcmd:
                - setenforce 0
                - systemctl stop firewalld
                - mkfs -t btrfs /dev/vdc
                - mkdir -p /var/lib/pgsql/
                - mount /dev/vdc /var/lib/pgsql/
                - chown -R postgres:postgres /var/lib/pgsql/
                - dnf -y install postgresql-server postgresql-contrib
                - postgresql-setup --initdb --unit postgresql
                - systemctl start postgresql
                - systemctl enable postgresql
                - sudo -u postgres psql -c "CREATE USER inventory WITH PASSWORD 'inventory';"
                - sudo -u postgres psql -c "CREATE DATABASE inventory OWNER inventory;"
              ssh_pwauth: true
              chpasswd:
              user: root
              password: password
              chpasswd: { expire: False }
          name: cloudinitdisk
        - dataVolume:
            name: inventory-db-dbdata
          name: dbdata
