kind: KafkaTopic
apiVersion: kafka.strimzi.io/v1beta2
metadata:
  name: orders
  labels:
    strimzi.io/cluster: my-cluster
  namespace: amq-streams
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
